name: CI
on: [push]
jobs:
  test:
    name: Test on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [8, 10, 12]
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node_version }}
    - name: Install
      run: yarn
    - name: Build
      run: yarn build
    - name: Test
      run: yarn test
    - name: Bundle Size
      run: yarn bundlesize
    - name: Publish Canary
      env: # Or as an environment variable
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      run: |
          echo "Fork PR: ${{github.repository}}"
          if [ "${{github.repository}}" == "Urigo/SOFA" ] && [ "${{ secrets.NODE_AUTH_TOKEN }}" != "" ]
          then
              echo "//registry.npmjs.org/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}" > .npmrc
              npm run ci:release:canary
          else    
              echo "Skipping canary publish due to a fork/PR..."
          fi    
