name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  test:
    name: Test on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [18, 20, 22, 23]
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v4.3.0
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install
        run: yarn --ignore-engines
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
