name: pr
on:
  pull_request:
    branches:
      - master

jobs:
  algolia:
    uses: the-guild-org/shared-config/.github/workflows/algolia-integrity.yml@main
    with:
      domain: https://www.the-guild.dev/graphql/sofa-api/
      source: 'SOFA'
      setupEnvWorkingDirectory: './website'
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
