name: website

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deployment:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository || github.event_name == 'push'
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: the-guild-org/shared-config/setup@main
        name: setup env
        with:
          nodeVersion: 18 # change if needed
          packageManager: yarn # change if needed

      - uses: the-guild-org/shared-config/website-cf@main
        name: build and deploy website
        env:
          NEXT_BASE_PATH: ${{ github.ref == 'refs/heads/master' && '/graphql/sofa-api' || '' }}
          SITE_URL: ${{ github.ref == 'refs/heads/master' && 'https://the-guild.dev/graphql/sofa-api' || '' }}
        with:
          cloudflareApiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflareAccountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: sofa
          prId: ${{ github.event.pull_request.number }}
          websiteDirectory: ./
          buildScript: cd website && yarn && yarn build
          artifactDir: website/out
