name: Website Deployment
on:
  push:
    branches:
      - master

jobs:
  deploy-website:
    name: Deploy Website
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[deploy_website]') || contains(github.ref, 'refs/tags/')
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2
      - name: Configure Git Credientials
        run: |
          git config --global user.email "theguild-bot@users.noreply.github.com"
          git config --global user.name "theguild-bot"
          echo "machine github.com login theguild-bot password ${{secrets.GITHUB_TOKEN}}" > ~/.netrc
      - name: Add origin remote and refetch master
        run: |
          git remote rm origin
          git remote add origin "https://github.com/${{github.repository}}"
          git fetch
          git checkout master
          git reset --hard
      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Yarn
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-15-15-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-15-15-yarn-
      - name: Deploy 🚀
        run: cd website && yarn && yarn deploy
        env:
          GIT_USER: theguild-bot
